[package]
name = "causal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
com= {path =  "../com"}
redis_store= {path =  "../redis_store"}
net={path = "../net"}
